[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/"
  to = "/en"
  status = 302

[[redirects]]
  from = "/:locale/*"
  to = "/:locale/:splat"
  status = 200

[[redirects]]
  from = "/:locale"
  to = "/:locale/"
  status = 200

# Handle language switching
[[redirects]]
  from = "/api/locale/:locale/*"
  to = "/:locale/:splat"
  status = 302

# Fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
