import { defineType, defineField } from "sanity"

export default defineType({
  name: "amenity",
  title: "Amenity",
  type: "document",
  fields: [
    defineField({
      name: "title",
      type: "localizedString",
      validation: r => r.required(),
    }),
    defineField({
      name: "icon",
      type: "string",
      options: {
        list: [
          "Waves",
          "TreePalm",
          "Flower2",
          "Church",
          "Building2",
          "Home",
          "Building",
          "Star",
          "Umbrella",
          "Sun",
          "Utensils",
          "Wine",
          "GlassWater",
          "Flame",
          "UtensilsCrossed",
          "Music",
          "Disc3",
          "Lightbulb",
          "Speaker",
          "Camera",
          "Snowflake",
          "Wifi",
          "Gem",
          "Car",
          "BedDouble",
          "Bus",
          "Plane",
          "ShieldCheck",
          "Key",
          "CalendarCheck",
          "Sparkles",
          "Scissors",
          "BookOpenCheck",
          "Accessibility",
        ],
      },
      description: "Lucide icon name (optional)",
    }),
  ],
  preview: {
    select: {
      title: "title.en",
      icon: "icon",
    },
  },
})
